# CMake generated Testfile for 
# Source directory: /home/hamid/Documents/project/HamDB
# Build directory: /home/hamid/Documents/project/HamDB
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("_deps/googletest-build")
subdirs("src/common")
subdirs("src/storage")
subdirs("src/utils")
subdirs("src/database")
subdirs("src/buffer")
subdirs("src/index")
subdirs("src/transaction")
subdirs("src/wal")
subdirs("src/catalog")
subdirs("src/executor")
subdirs("src/parser")
subdirs("src/binder")
subdirs("src/planner")
subdirs("src/optimizer")
subdirs("src/shell")
subdirs("src/prepared")
subdirs("src/server")
subdirs("tests/storage")
subdirs("tests/utils")
subdirs("tests/buffer")
subdirs("tests/index")
subdirs("tests/transaction")
subdirs("tests/wal")
subdirs("tests/catalog")
subdirs("tests/executor")
subdirs("tests/parser")
subdirs("tests/binder")
subdirs("tests/planner")
subdirs("tests/optimizer")
subdirs("tests/shell")
subdirs("tests/prepared")
subdirs("tests/server")
subdirs("examples")
subdirs("app")
