if(EXISTS "/home/hamid/Documents/project/HamDB/tests/catalog/catalog_test[1]_tests.cmake")
  include("/home/hamid/Documents/project/HamDB/tests/catalog/catalog_test[1]_tests.cmake")
else()
  add_test(catalog_test_NOT_BUILT catalog_test_NOT_BUILT)
endif()
