add_executable(planner_test planner_test.cpp)
target_include_directories(planner_test PRIVATE ${PROJECT_SOURCE_DIR}/include)
target_link_libraries(planner_test PRIVATE GTest::gtest_main hamdb_planner hamdb_binder)
add_test(NAME PlannerTest COMMAND planner_test)

add_executable(physical_planner_test physical_planner_test.cpp)
target_include_directories(physical_planner_test PRIVATE ${PROJECT_SOURCE_DIR}/include)
target_link_libraries(physical_planner_test PRIVATE GTest::gtest_main hamdb_planner hamdb_binder)
add_test(NAME PhysicalPlannerTest COMMAND physical_planner_test)

add_executable(executor_factory_test executor_factory_test.cpp)
target_include_directories(executor_factory_test PRIVATE ${PROJECT_SOURCE_DIR}/include)
target_link_libraries(executor_factory_test PRIVATE GTest::gtest_main hamdb_planner hamdb_binder hamdb_executor hamdb_transaction hamdb_wal hamdb_parser)
add_test(NAME ExecutorFactoryTest COMMAND executor_factory_test)
